import Head from "next/head";
import Navbar from './navbar'
import Hero from './hero'
import About from './about'
import Support from './support'
import Alltogether from './alltogther'
import Pricing from './pricing'
import Footer from './footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Navbar />
        <Hero />
        <About />
        <Support />
        <Alltogether />
        <Pricing />
        <Footer />
      </>
    </div>
  );
}
